theme: jekyll-theme-minimal
permalink: /support.md/
permalink: /downloads.md/
permalink: /about.md/
permalink: pretty
permalink: /addcard.html/
permalink: /purchase.html/
permalink: /paymenthelp.md/
permalink: /PayForSchoolVM.md/
permalink: /FAQ.md/
